### PR TITLE
added xvfb to casa6 images

### PR DESCRIPTION
**Pull request by o-smirnov**

### CODE REVIEW

**Review by Athanaseus — DISMISSED** [review]
LGTM!

**Comment by tmolteno** [comment]
This runs into two issues:

## Separate Executables

The pip install of casa6 no longer has separate executables for each tool. see [here](https://casadocs.readthedocs.io/en/stable/notebooks/usingcasa.html#Starting-CASA). A wrapper for each command could be generated

## External Data

External data is required by casa6. Typically an 800MB download. This can be manually added to the Dockerfile using the following commands see [here](https://casadocs.readthedocs.io/en/stable/notebooks/external-data.html#Populating-the-Data-Directory-Manually)

```
!python -m casaconfig --update-all
!python -m casaconfig --current-data
```

This should stop it auto updating, and freeze the data at the moment when the container was created.

**Comment by o-smirnov** [comment]
OK, needs a few more fixes, incoming soon -- then we'll ask for a re-review.

**Comment by o-smirnov** [comment]
Hi @tmolteno, I have written this very simple test recipe to print the configured measures path:
```yml
cabs:
  casatest:
    image:
      name: casa6
      version: cc0.1.3
    flavour:
      kind: python-code
      interpreter_binary: python3.8
    command: |
      from casaconfig import config
      print(config.measurespath)
```

With the latest casa6 image, it gives me what I expect:
```
### running                                                                                                                                                                                                      
# /opt/casa/data
```                                                                                                                                                                                                 

I'll try running an actual casa6 task next.

**Comment by tmolteno** [comment]
```
docker pull quay.io/stimela2/casa6:cc0.1.3
docker run -it quay.io/stimela2/casa6:cc0.1.3
```
Now I get an error 
```
>>> import casatasks
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/casatasks/__init__.py", line 5, in <module>
    from casatools import logsink as _logsink
  File "/usr/local/lib/python3.8/dist-packages/casatools/__init__.py", line 175, in <module>
    raise ImportError('measures data is not available, visit http://go.nrao.edu/casadata-info for more information')
ImportError: measures data is not available, visit http://go.nrao.edu/casadata-info for more information
>>> 
```

**Comment by tmolteno** [comment]
Within the docker container, I can do the following and everything works.

```
root@f44377c91f2c:/# pip install casadata
Collecting casadata
  Downloading casadata-2024.8.26-py3-none-any.whl (349.3 MB)
     |████████████████████████████████| 349.3 MB 24.2 MB/s 
Installing collected packages: casadata
Successfully installed casadata-2024.8.26
root@f44377c91f2c:/# python3.8
Python 3.8.10 (default, Nov  7 2024, 13:10:47) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import casatools
>>> 
```

**Comment by tmolteno** [comment]
@o-smirnov , I have a fix that appears to work. This is related to using the system installed python3-casacore. The trick is to do the following in the container definition for casa6

* CASASITECONFIG="/opt/casa/casasiteconfig.py"
* pip install casadata



Then set up casasiteconfig.py as

```
import casadata
measurespath = casadata.datapath
measures_auto_update = False
data_auto_update = False
```

Casa now uses the casadata packages data.

I have tested this with singularity using the following definition

```
Bootstrap: docker
From:kernsuite/base:8

%environment
    CASASITECONFIG="/opt/casa/casasiteconfig.py"

%files
    casasiteconfig.py /opt/casa/casasiteconfig.py
%post
    apt update
    apt upgrade -y
    apt install -y python3-casacore python3-pip libblas-dev liblapack-dev
    pip3 install --upgrade --no-cache-dir numpy casatools casatasks casaconfig casadata
```

The pip install --upgrade numpy seems to be needed, as do the libblas-dev and liblapack-dev

**Comment by o-smirnov** [comment]
Ah thanks @tmolteno! I've incorporated this into the new casa6 image -- could you please pull and try again?

**Comment by tmolteno** [comment]
Success. Split and listobs now work. I will change remaining cabs and commit.

**Comment by o-smirnov** [comment]
Minor fixes, @Athanaseus @SpheMakh please re-review.

**Review by Athanaseus — APPROVED** [review]

**Pull request merged**
